export const MASKS = [
  { id: 'solar', heroWide: 'assets/hero-eclipse.png', essence: "When the horizon breaks, she is already there. Solar is Nyota at full light, the celebration that needs no permission. Her sets open like sunrise: slow gold, then heat, then everything at once. She plays for the moment you stop watching and start rising.", appears: "Daytime festivals · rooftop rituals · the first set after a long winter", ritual: [{"name":"The Ascent","text":"Warm tribal drums gather the crowd like first light on a hillside."},{"name":"The Blaze","text":"Uplifting Afro House at full radiance, hands open, eyes closed."},{"name":"The Glow","text":"She leaves you warm. The light stays long after the set ends."}],  name: 'SOLAR', line: "When it's time to rise.", motto: 'Rise with the sun.', creed: ['We dance with the light.', 'We lead with love.', 'We rise together.'], figure: 'assets/form-solar.png', dj: 'assets/dj-solar.png', traits: ['Radiant', 'Confident', 'Joyful'], sound: ['Afro House', 'Tribal', 'Uplifting'], setTitle: 'Afro House Set', setElements: 'Day · Sun · Fire', setKey: 'Celebration', poster: 'uploads/ChatGPT Image May 18, 2026, 02_26_31 PM.png', img: 'assets/solar_m.png', alt: 'uploads/Solar.png', accent: '#d4a437', accentDeep: '#a5761c', glow: 'rgba(212,164,55,.22)' },
  { id: 'lunar', heroWide: 'assets/hero-lunar.png', essence: "She arrives when the noise falls away. Lunar is the inward tide: melodic, deep, unhurried. Her sets are for the feelings you carry but cannot name. She does not lift you; she holds you, and lets the water do the rest.", appears: "Late-night rooms · full-moon gatherings · the hour before sunrise", ritual: [{"name":"The Descent","text":"Deep, melodic openings that lower the room's pulse to hers."},{"name":"The Tide","text":"Soulful waves that pull memory to the surface and let it move."},{"name":"The Surfacing","text":"You come back lighter than you went down."}], creed: ["We feel before we know.","We heal in the dark.","We move by moonlight."],  name: 'LUNAR', line: "When it's time to feel.", motto: 'Move by moonlight.', figure: 'assets/form-lunar.png', dj: 'assets/dj-lunar.png', traits: ['Intuitive', 'Feminine', 'Healing'], sound: ['Melodic House', 'Deep', 'Soulful'], setTitle: 'Healing Set', setElements: 'Night · Moon · Water', setKey: 'Inspiration', poster: 'uploads/ChatGPT Image May 18, 2026, 02_26_28 PM.png', img: 'assets/lunar_m.png', alt: 'uploads/Lunar_Plain.png', accent: '#b8a7d9', accentDeep: '#7c6aa8', glow: 'rgba(184,167,217,.22)' },
  { id: 'rhythm', heroWide: 'assets/hero-rhythm.png', essence: "Rhythm is the body's answer to every question. She is Nyota mid-festival, playful and electric, impossible to stand still near. Her sets are a conversation in drums: she asks, and ten thousand feet reply.", appears: "Festival mainstages · street carnivals · anywhere the ground can shake", ritual: [{"name":"The Call","text":"A single drum line, repeated until the crowd answers back."},{"name":"The Pulse","text":"Afro Tech at full charge. One groove, one body, no edges."},{"name":"The Release","text":"She drops the floor out and the whole field lifts off it."}], creed: ["We are one pulse.","We speak in drums.","We never stand still."],  name: 'RHYTHM', line: "When it's time to move.", motto: 'Feel the pulse.', figure: 'assets/form-rhythm.png', dj: 'assets/dj-rhythm.png', traits: ['Energetic', 'Playful', 'Connecting'], sound: ['Afro Tech', 'Festival', 'Groovy'], setTitle: 'Festival Set', setElements: 'Energy · Crowd · Pulse', setKey: 'Movement', poster: 'uploads/ChatGPT Image May 18, 2026, 02_26_27 PM.png', img: 'assets/rhythm_m.png', alt: 'uploads/Nyota_Rhythm.jpg', accent: '#53c7c0', accentDeep: '#23847e', glow: 'rgba(83,199,192,.20)' },
  { id: 'ancestor', heroWide: 'assets/hero-ancestor.png', essence: "Before the beat, there was the drum. Ancestor is Nyota remembering: organic, rooted, sacred. Her sets reach backward to move forward: rhythms carried across oceans, played loud for the ones who could not stay.", appears: "Intimate ceremonies · exclusive gatherings · nights of remembrance", ritual: [{"name":"The Calling","text":"Organic textures and root rhythms summon the room to stillness."},{"name":"The Offering","text":"Sacred grooves passed hand to hand, generation to generation."},{"name":"The Blessing","text":"You leave carrying someone else's fire. That is the point."}], creed: ["We remember the ones before.","We carry their fire.","We dance because they dreamed."],  name: 'ANCESTOR', line: "When it's time to remember.", motto: 'We dance because they dreamed.', figure: 'assets/form-ancestor.png', dj: 'assets/dj-ancestor.png', traits: ['Wise', 'Grounded', 'Grateful'], sound: ['Organic House', 'Roots', 'Sacred'], setTitle: 'Exclusive Event', setElements: 'Roots · Spirit · Wisdom', setKey: 'Connection', poster: 'uploads/ChatGPT Image May 18, 2026, 02_26_25 PM.png', img: 'assets/ancestor_m.png', alt: 'uploads/Ancestor_Plain.png', accent: '#8c6239', accentDeep: '#8c6239', glow: 'rgba(140,98,57,.28)' },
  { id: 'eclipse', heroWide: 'assets/hero-eclipse-form.png', essence: "Some nights ask for both. Eclipse is Nyota at the threshold, light and shadow in a single body, techno with a heartbeat. Her sets are a passage: you enter as one thing and you leave as another.", appears: "Warehouse depths · closing sets · the longest nights of the year", ritual: [{"name":"The Threshold","text":"Progressive layers dim the light until only the pulse remains."},{"name":"The Dark","text":"Driving techno at the bottom of the night. The turning point."},{"name":"The Return","text":"Dawn in the mix. Light and shadow, finally one."}], creed: ["We hold both light and shadow.","We end to begin.","We become one."],  name: 'ECLIPSE', line: 'When light and shadow become one.', motto: 'Light and shadow become one.', figure: 'assets/form-eclipse.png', dj: 'assets/dj-eclipse.png', traits: ['Balance', 'Transformation', 'Magic'], sound: ['Techno', 'Progressive', 'Journey'], setTitle: 'Techno Set', setElements: 'Dark · Duality · Transform', setKey: 'Rebirth', poster: 'uploads/ChatGPT Image May 18, 2026, 02_26_22 PM.png', img: 'assets/eclipse_m.png', alt: 'uploads/Eclispe_Plain.png', accent: '#d4b76a', accentDeep: '#1b1d2e', glow: 'rgba(201,179,126,.20)' }
];
export const ADAPTS = ['Masks shift her energy', 'Music matches the phase', 'Each set is a ritual', 'Each experience is unique', 'Nyota is the cycle'];
export const LINKS = {
  instagram: 'https://www.instagram.com/nyotamuzik/',
  spotify: 'https://open.spotify.com/artist/4nv8RpsA8VQ7mVHj90q1jl',
  youtube: 'https://www.youtube.com/@NyotaMuzik',
  latestVideo: 'https://youtu.be/Cx1KGbow2iI',
  latestEmbed: 'https://www.youtube.com/embed/Cx1KGbow2iI',
  latestThumb: 'https://i.ytimg.com/vi/Cx1KGbow2iI/maxresdefault.jpg'
};
export const RELEASE = { title: 'Take Me Back', type: 'Latest Release' };
