// MorrMoto — Research capture #1, 2026-10-04.
// Every source and candidate below was found via live web search on 2026-10-04.
// Evidence = paraphrased facts from the search snippet; pages were NOT fetched or crawled.
// page_age_days = age of the indexed page as reported by the search index (null = unknown).
export const CAPTURE = {
  id: 'capture-001',
  captured_at: '2026-10-04T15:00:00-05:00',
  method: 'Search discovery (manual research session)',
  automated: false,
  note: 'No scheduled crawler is running yet. These records are real discoveries from public pages, captured by hand through a search index. They are not simulated.'
};

export const WINDOW = { start: '2026-10-04', end: '2026-11-03' };

export const SOURCES = [
  { id:'cota', name:'Circuit of The Americas — events calendar', url:'https://circuitoftheamericas.com/events/', type:'Venue (official)', primary:true, area:'Austin (Del Valle)', categories:['Major Motorsport','Track Day'], method:'Public HTML', freq:'Daily', last_checked:'2026-10-04', reliability:0.95, active:true, notes:'Mixes concerts and bicycle events with motorsport; classifier must filter non-motor items.' },
  { id:'msr-cota', name:'MotorsportReg — COTA venue page', url:'https://www.motorsportreg.com/venues/circuit-of-americas-austin-tx', type:'Registration platform', primary:false, area:'Austin', categories:['Track Day','Race','Show'], method:'Public HTML (request MSR calendar/API access)', freq:'Daily', last_checked:'2026-10-04', reliability:0.9, active:true, notes:'Organizer-entered data. Best single source for track days and club racing.' },
  { id:'msr-h2r', name:'MotorsportReg — Harris Hill Road venue page', url:'https://www.motorsportreg.com/venues/harris-hill-road-san-marcos-tx', type:'Registration platform', primary:false, area:'San Marcos', categories:['Track Day','Autocross'], method:'Public HTML (request MSR calendar/API access)', freq:'Daily', last_checked:'2026-10-04', reliability:0.9, active:true, notes:'Also surfaces Texas Spokes Sports Car Club events.' },
  { id:'h2r', name:'Harris Hill Raceway', url:'http://www.harrishillroad.com', type:'Venue (official)', primary:true, area:'San Marcos', categories:['Track Day','Race'], method:'Public HTML', freq:'Daily', last_checked:null, reliability:0.95, active:true, notes:'Not fetched yet. Events at this track are currently corroborated only through MSR and Track Night in America.' },
  { id:'tnia', name:'Track Night in America — events', url:'https://www.tracknightinamerica.com/events', type:'Organizer', primary:true, area:'National (Harris Hill)', categories:['Track Day'], method:'Public HTML', freq:'Weekly', last_checked:'2026-10-04', reliability:0.9, active:true, notes:'SCCA program. Dated listings with venue.' },
  { id:'scca-loc', name:'SCCA — Harris Hill location page', url:'https://www.scca.com/locations/1984328-harris-hill-raceway', type:'Sanctioning body', primary:false, area:'San Marcos', categories:['Track Day','Race'], method:'Public HTML', freq:'Weekly', last_checked:'2026-10-04', reliability:0.85, active:true, notes:'Same publisher as Track Night in America, so it does not count as independent.' , publisher:'scca' },
  { id:'txscca', name:'Texas Region SCCA — events', url:'https://www.texasscca.org/events/', type:'Club calendar', primary:true, area:'DFW', categories:['Autocross','Track Day'], method:'Structured data (JSON-LD Event)', freq:'Weekly', last_checked:'2026-10-04', reliability:0.85, active:true, notes:'Club is DFW-based, so most events fall outside coverage. Page HTML and JSON-LD disagree on a date.' },
  { id:'racingcal', name:'racingcalendar.net — Harris Hill', url:'https://racingcalendar.net/circuit/harris-hill-raceway', type:'Aggregator', primary:false, area:'San Marcos', categories:['Race'], method:'Public HTML', freq:'Weekly', last_checked:'2026-10-04', reliability:0.6, active:true, notes:'Club race series dates.' },
  { id:'lra', name:'Longhorn Racing Academy — Harris Hill', url:'https://www.longhornracingacademy.com/track/harris-hill-raceway/', type:'Commercial experience', primary:true, area:'San Marcos', categories:['Driving Experience'], method:'Public HTML', freq:'Weekly', last_checked:'2026-10-04', reliability:0.8, active:true, notes:'Paid exotic-car driving experience. Relevance to enthusiasts needs a human call.' },
  { id:'racingamerica', name:'Racing America @ COTA', url:'https://events.racingamerica.com/events/2026-cota/', type:'Organizer', primary:true, area:'Austin', categories:['Race','Show'], method:'Public HTML', freq:'Weekly', last_checked:'2026-10-04', reliability:0.95, active:true, notes:'Vintage racing, Trans Am and a car show.' },
  { id:'wiki', name:'Wikipedia — 2026 series calendars', url:'https://en.wikipedia.org/wiki/2026_Porsche_Carrera_Cup_North_America', type:'Reference', primary:false, area:'National', categories:['Race'], method:'API (MediaWiki)', freq:'Weekly', last_checked:'2026-10-04', reliability:0.6, active:true, notes:'For corroboration only. Never the sole source for a published event.', corroborationOnly:true },
  { id:'gtacc', name:'Georgetown Texas Area Car Club — local monthly events', url:'https://gtacc.org/local-monthly-events', type:'Club calendar', primary:false, area:'Georgetown / Round Rock / Pflugerville', categories:['Show','Cars & Coffee'], method:'Public HTML', freq:'Weekly', last_checked:'2026-10-04', reliability:0.8, active:true, notes:'Lists recurring meets by rule (for example, "3rd Sunday"). The page layout makes time extraction ambiguous.' },
  { id:'ci', name:'Community Impact — "6 area car shows"', url:'https://communityimpact.com/south-central-austin/events/check-out-these-6-area-car-shows/', type:'Local news', primary:false, area:'Austin metro', categories:['Show','Cars & Coffee'], method:'Public HTML', freq:'Monthly', last_checked:'2026-10-04', reliability:0.5, active:true, notes:'Article is about 850 days old. Use it for leads, not for verification.' },
  { id:'motortexas', name:'MotorTexas — event listings', url:'http://www.motortexas.com/event/324', type:'Aggregator', primary:false, area:'Texas', categories:['Show'], method:'Public HTML', freq:'Weekly', last_checked:'2026-10-04', reliability:0.65, active:true, notes:'Its "more events" links are a useful discovery fan-out.' },
  { id:'goroundrock', name:'Go Round Rock — events', url:'https://goroundrock.com/events/round-rock-car-show-2/2026-09-20/', type:'City tourism', primary:false, area:'Round Rock', categories:['Show'], method:'Public HTML (check for ICS export)', freq:'Weekly', last_checked:'2026-10-04', reliability:0.85, active:true, notes:'Explicit dated instances of recurring shows.' },
  { id:'ccf', name:'Car Cruise Finder — Pflugerville', url:'https://carcruisefinder.com/car-shows/tag/pflugerville-tx/', type:'Aggregator', primary:false, area:'Pflugerville', categories:['Show','Cruise'], method:'Public HTML', freq:'Weekly', last_checked:'2026-10-04', reliability:0.6, active:true, notes:'' },
  { id:'gog', name:'GetOutGarage — Round Rock / Pflugerville', url:'https://www.getoutgarage.com/events/car-shows/tx/round-rock', type:'Aggregator', primary:false, area:'Round Rock / Pflugerville / Hutto', categories:['Show','Meet'], method:'Public HTML', freq:'Weekly', last_checked:'2026-10-04', reliability:0.6, active:true, notes:'Some dates look machine-generated, for example a car show listed on a Monday.' },
  { id:'ctxm', name:'Central Texas Mopars — events', url:'https://www.centraltexasmopars.com/events-1', type:'Club calendar', primary:false, area:'Central Texas', categories:['Show','Club Event'], method:'Public HTML', freq:'Weekly', last_checked:'2026-10-04', reliability:0.75, active:true, notes:'Indexed snapshot shows 2025 dates, so its content is stale.' },
  { id:'cowboyhd', name:'Cowboy Harley-Davidson of Austin — events', url:'https://www.cowboyharleyaustin.com/events-calendar-harley-davidson-dealership--xlistevents', type:'Dealer', primary:true, area:'South Austin', categories:['Bike Night','Dealer Event'], method:'Public HTML', freq:'Weekly', last_checked:'2026-10-04', reliability:0.85, active:true, notes:'Indexed snapshot covers July–September 2026 only. October dates are expanded from the stated recurrence.' },
  { id:'bnusa', name:'Bike Night USA — Cycle Gear Austin', url:'https://bikenightusa.com/events/view/kxrnWm8pLg/cycle-gear-austin-june-bike-night', type:'Aggregator', primary:false, area:'Austin', categories:['Bike Night'], method:'Public HTML', freq:'Weekly', last_checked:'2026-10-04', reliability:0.6, active:true, notes:'Listing is the June instance, with the recurrence stated in its text.' },
  { id:'meetup', name:'Meetup — motorcycle riding near Austin', url:'https://www.meetup.com/find/us--tx--austin/motorcycle-riding/', type:'Platform', primary:false, area:'Austin', categories:['Group Ride','Bike Night'], method:'API (Meetup GraphQL — requires OAuth/Pro; evaluate)', freq:'Daily', last_checked:'2026-10-04', reliability:0.7, active:true, notes:'Group rides by Renegade Riders, the Sons and others. Indexed snapshot is from July.' },
  { id:'ama', name:'Austin Moto Adventures — TouraTexas Rally', url:'https://austinmotoventures.com/touratexas-rally/', type:'Organizer', primary:true, area:'Burnet (Worth the Drive)', categories:['Rally','Off-road'], method:'Structured data (JSON-LD Event)', freq:'Weekly', last_checked:'2026-10-04', reliability:0.95, active:true, notes:'Clean JSON-LD with start and end timestamps.' },
  { id:'lsru', name:'Lonestar Rod & Kustom Round Up', url:'https://lonestarroundup.com', type:'Organizer', primary:true, area:'Austin', categories:['Show','Swap Meet'], method:'Public HTML', freq:'Monthly', last_checked:'2026-10-04', reliability:0.95, active:true, notes:'Annual event in April. The 2026 edition is past. Recheck in January for 2027.' },
  { id:'culturemap', name:'CultureMap Austin — events', url:'https://austin.culturemap.com/eventdetail/the-lonestar-round-up/', type:'Local media', primary:false, area:'Austin', categories:['Show'], method:'Public HTML', freq:'Weekly', last_checked:'2026-10-04', reliability:0.7, active:true, notes:'' },
  { id:'hfap', name:'Hidden Falls Adventure Park', url:'https://www.hiddenfallsadventurepark.com/', type:'Venue (off-road park)', primary:true, area:'Marble Falls (Worth the Drive)', categories:['Off-road'], method:'Public HTML', freq:'Weekly', last_checked:'2026-10-04', reliability:0.9, active:true, notes:'Venue confirmed, but no event calendar was found. This is the main off-road coverage gap.' },
  { id:'breakfastclub', name:'Breakfast Club ATX', url:'https://breakfastclubatx.com/', type:'Club', primary:true, area:'Austin', categories:[], method:'Public HTML', freq:'—', last_checked:'2026-10-04', reliability:0.8, active:false, notes:'Bicycle group rides, so out of scope. Deactivated after one check.' },
  // Targets — identified, not yet checked
  { id:'eventbrite', name:'Eventbrite', url:'https://www.eventbrite.com/', type:'Platform', primary:false, area:'Austin', categories:[], method:'API (organization-scoped only; public search API deprecated)', freq:'Daily', last_checked:null, reliability:0.7, active:true, notes:'Target. Public discovery means searching listing pages, which needs a ToS review first.' },
  { id:'reddit', name:'Reddit — r/Austin', url:'https://www.reddit.com/r/Austin/', type:'Community', primary:false, area:'Austin', categories:[], method:'API (OAuth, rate-limited)', freq:'Daily', last_checked:null, reliability:0.4, active:true, notes:'Target. Use for leads only; never a sole source.' },
  { id:'instagram', name:'Instagram — organizer accounts', url:'https://www.instagram.com/', type:'Social', primary:false, area:'Austin', categories:[], method:'Manual / community submission', freq:'—', last_checked:null, reliability:0.6, active:true, notes:'No compliant API for third-party discovery. Many meets announce only here, so submissions are essential.' },
  { id:'facebook', name:'Facebook Events / Groups', url:'https://www.facebook.com/events/', type:'Social', primary:false, area:'Austin', categories:[], method:'Manual / community submission', freq:'—', last_checked:null, reliability:0.6, active:true, notes:'No public events API. The Round Rock Car Show defers updates to its FB page.' },
  { id:'pflugerville', name:'City of Pflugerville — events', url:'https://www.pflugervilletx.gov/', type:'City calendar', primary:true, area:'Pflugerville', categories:['Cars & Coffee'], method:'Public HTML (check for ICS)', freq:'Weekly', last_checked:null, reliability:0.9, active:true, notes:'Target. Co-host of Coffee & Pfuel.' },
  { id:'georgetown', name:'City of Georgetown — events', url:'https://georgetown.org/', type:'City calendar', primary:true, area:'Georgetown', categories:['Show'], method:'Public HTML (check for ICS)', freq:'Weekly', last_checked:null, reliability:0.9, active:true, notes:'Target. Would give primary confirmation for Pistons on the Square.' }
];

const R = (nth, weekday, inferred=false) => ({ freq:'monthly_nth', nth, weekday, inferred });
const T = '2026-10-04T15:00:00-05:00';

// extracted: never invent. null = unknown.
export const CANDIDATES = [
  { id:'c01', source_id:'cota', url:'https://circuitoftheamericas.com/event/f1/', raw_title:'Formula 1 United States Grand Prix', page_age_days:4, evidence:'Official event page: October 22–25, 2026; tickets on sale.', extracted:{ event_name:'Formula 1 United States Grand Prix', start_date:'2026-10-22', end_date:'2026-10-25', venue:'Circuit of The Americas', city:'Austin', organizer:'Circuit of The Americas', event_type:['Major Motorsport','Race'], vehicle_type:['Cars'], free:false, registration_required:true, registration_url:'https://circuitoftheamericas.com/event/f1/tickets/' } },
  { id:'c02', source_id:'cota', url:'https://circuitoftheamericas.com/event/f1/tickets/', raw_title:'Formula 1 Tickets', page_age_days:18, evidence:'Ticket page: October 22–25, 2026.', extracted:{ event_name:'Formula 1 United States Grand Prix', start_date:'2026-10-22', end_date:'2026-10-25', venue:'Circuit of The Americas', city:'Austin', organizer:'Circuit of The Americas', event_type:['Major Motorsport','Race'], vehicle_type:['Cars'], free:false, registration_required:true } },
  { id:'c03', source_id:'msr-cota', url:'https://www.motorsportreg.com/venues/circuit-of-americas-austin-tx', raw_title:'NEQ Social - Formula1 US Grand-Prix in Austin, TX', page_age_days:null, evidence:'MSR listing typed Festival/Social, Fri Oct 23 – Sun Oct 25, at COTA.', extracted:{ event_name:'NEQ Social — F1 US Grand Prix', start_date:'2026-10-23', end_date:'2026-10-25', venue:'Circuit of The Americas', city:'Austin', organizer:'NEQ Social', event_type:['Meet'], vehicle_type:['Cars'] } },
  { id:'c04', source_id:'wiki', url:'https://en.wikipedia.org/wiki/2026_Porsche_Carrera_Cup_North_America', raw_title:'2026 Porsche Carrera Cup North America — Round 8', page_age_days:null, evidence:'Season calendar: round 8 at Circuit of the Americas, October 23–25.', extracted:{ event_name:'Porsche Carrera Cup North America — Round 8', start_date:'2026-10-23', end_date:'2026-10-25', venue:'Circuit of The Americas', city:'Austin', organizer:null, event_type:['Race'], vehicle_type:['Cars','Euro'] } },
  { id:'c05', source_id:'cota', url:'https://circuitoftheamericas.com/bike-night/', raw_title:'Bike Night', page_age_days:220, evidence:'"Clip in and cycle the circuit": bicycle ride on the track, 6PM to dusk, October 6.', extracted:{ event_name:'Bike Night at COTA', start_date:'2026-10-06', start_time:'18:00', venue:'Circuit of The Americas', city:'Austin', organizer:'Circuit of The Americas', event_type:['Other'], vehicle_type:[], motorized:false, price:'$120 season pass' } },
  { id:'c06', source_id:'msr-cota', url:'https://www.motorsportreg.com/venues/circuit-of-americas-austin-tx', raw_title:'Chin Track Days @ Circuit of The Americas', page_age_days:null, evidence:'MSR listing: Sat Oct 3 – Sun Oct 4, COTA.', extracted:{ event_name:'Chin Track Days @ COTA', start_date:'2026-10-03', end_date:'2026-10-04', venue:'Circuit of The Americas', city:'Austin', organizer:'Chin Track Days', event_type:['Track Day'], vehicle_type:['Motorcycles'], registration_required:true } },
  { id:'c07', source_id:'msr-cota', url:'https://www.motorsportreg.com/venues/circuit-of-americas-austin-tx', raw_title:'Chin Track Days @ Circuit of The Americas', page_age_days:null, evidence:'MSR listing: Sat Nov 14 – Sun Nov 15, COTA, HPDE.', extracted:{ event_name:'Chin Track Days @ COTA', start_date:'2026-11-14', end_date:'2026-11-15', venue:'Circuit of The Americas', city:'Austin', organizer:'Chin Track Days', event_type:['Track Day'], vehicle_type:['Motorcycles'], registration_required:true } },
  { id:'c08', source_id:'racingamerica', url:'https://events.racingamerica.com/events/2026-cota/', raw_title:'Garage Living Presents 2026 Racing America @ COTA', page_age_days:null, evidence:'November 6–8, 2026: Trans Am, historic and vintage racing, and a car show with touring laps.', extracted:{ event_name:'Racing America @ COTA', start_date:'2026-11-06', end_date:'2026-11-08', venue:'Circuit of The Americas', city:'Austin', organizer:'Racing America', event_type:['Race','Show'], vehicle_type:['Cars','Classics','American','Euro'], registration_required:false } },
  { id:'c09', source_id:'msr-cota', url:'https://www.motorsportreg.com/venues/circuit-of-americas-austin-tx', raw_title:'2026 Racing America @ COTA', page_age_days:null, evidence:'MSR listing by SVRA: Thu Nov 5 – Sun Nov 8, Vintage Racing.', extracted:{ event_name:'Racing America @ COTA', start_date:'2026-11-05', end_date:'2026-11-08', venue:'Circuit of The Americas', city:'Austin', organizer:'SVRA', event_type:['Race'], vehicle_type:['Classics'] } },
  { id:'c10', source_id:'wiki', url:'https://en.wikipedia.org/wiki/2026_Trans-Am_Series', raw_title:'2026 Trans-Am Series — Round 10, Circuit of the Americas', page_age_days:null, evidence:'Season finale at COTA, November 5–8.', extracted:{ event_name:'Trans-Am Series — COTA finale', start_date:'2026-11-05', end_date:'2026-11-08', venue:'Circuit of The Americas', city:'Austin', organizer:'SCCA Pro Racing', event_type:['Race'], vehicle_type:['Cars','American'] } },
  { id:'c11', source_id:'msr-cota', url:'https://www.motorsportreg.com/venues/circuit-of-americas-austin-tx', raw_title:'2026 COTA - Hagerty | Cars & Caffeine Car Show', page_age_days:null, evidence:'MSR listing by Racing America, Sat Nov 7, Car Show/Concours.', extracted:{ event_name:'Hagerty Cars & Caffeine Car Show at COTA', start_date:'2026-11-07', venue:'Circuit of The Americas', city:'Austin', organizer:'Racing America', event_type:['Show','Cars & Coffee'], vehicle_type:['Mixed'] } },
  { id:'c12', source_id:'tnia', url:'https://www.tracknightinamerica.com/events', raw_title:'Track Night 2026: Harris Hill Raceway - October 14', page_age_days:null, evidence:'Dated listing: October 14, 2026, Harris Hill Raceway, San Marcos.', extracted:{ event_name:'Track Night in America — Harris Hill', start_date:'2026-10-14', venue:'Harris Hill Raceway', street_address:'2840 Harris Hill Rd', city:'San Marcos', organizer:'SCCA Track Night in America', event_type:['Track Day'], vehicle_type:['Cars'], registration_required:true, latitude:29.918892, longitude:-97.873258 } },
  { id:'c13', source_id:'msr-h2r', url:'https://www.motorsportreg.com/venues/harris-hill-road-san-marcos-tx', raw_title:'Track Night 2026: Harris Hill Raceway - October 14', page_age_days:null, evidence:'MSR: Wed Oct 14, Harris Hill Road, HPDE.', extracted:{ event_name:'Track Night in America — Harris Hill', start_date:'2026-10-14', venue:'Harris Hill Raceway', street_address:'2840 Harris Hill Road', city:'San Marcos', organizer:'SCCA Track Night in America', event_type:['Track Day'], vehicle_type:['Cars'], registration_required:true } },
  { id:'c14', source_id:'scca-loc', url:'https://www.scca.com/locations/1984328-harris-hill-raceway', raw_title:'Track Night 2026: Harris Hill Raceway - October 14', page_age_days:null, evidence:'SCCA location page lists the Oct 14 Track Night.', extracted:{ event_name:'Track Night in America — Harris Hill', start_date:'2026-10-14', venue:'Harris Hill Raceway', city:'San Marcos', organizer:'SCCA', event_type:['Track Day'], vehicle_type:['Cars'] } },
  { id:'c15', source_id:'msr-h2r', url:'https://www.motorsportreg.com/venues/harris-hill-road-san-marcos-tx', raw_title:'Spokes Track Sprint @ Harris Hill Raceway', page_age_days:null, evidence:'MSR: Sun Oct 18, Texas Spokes Sports Car Club, Autocross/Solo.', extracted:{ event_name:'Spokes Track Sprint @ Harris Hill', start_date:'2026-10-18', venue:'Harris Hill Raceway', street_address:'2840 Harris Hill Road', city:'San Marcos', organizer:'Texas Spokes Sports Car Club', event_type:['Autocross','Club Event'], vehicle_type:['Cars'], registration_required:true } },
  { id:'c16', source_id:'racingcal', url:'https://racingcalendar.net/circuit/harris-hill-raceway', raw_title:'H2R 914 Challenge Series / H2R Miata Challenge Series', page_age_days:null, evidence:'Upcoming: 17 Oct 2026, both club series.', extracted:{ event_name:'H2R 914 & Miata Challenge Series', start_date:'2026-10-17', venue:'Harris Hill Raceway', city:'San Marcos', organizer:null, event_type:['Race'], vehicle_type:['Cars','Euro','JDM','Classics'] } },
  { id:'c17', source_id:'lra', url:'https://www.longhornracingacademy.com/track/harris-hill-raceway/', raw_title:'Harris Hill Raceway — Ferrari 296 GTB (next event Fri Oct 9)', page_age_days:null, evidence:'Driving-experience page: next events Fri Oct 9 and Sat Oct 24.', flags:['commercial'], extracted:{ event_name:'Longhorn Racing Academy — exotic drive day', start_date:'2026-10-09', venue:'Harris Hill Raceway', city:'San Marcos', organizer:'Longhorn Racing Academy', event_type:['Driving Experience'], vehicle_type:['Exotics'], free:false, registration_required:true } },
  { id:'c18', source_id:'lra', url:'https://www.longhornracingacademy.com/track/harris-hill-raceway/', raw_title:'Harris Hill Raceway — Ferrari 296 GTB (Sat Oct 24)', page_age_days:null, evidence:'Same page, second date: Sat Oct 24.', flags:['commercial'], extracted:{ event_name:'Longhorn Racing Academy — exotic drive day', start_date:'2026-10-24', venue:'Harris Hill Raceway', city:'San Marcos', organizer:'Longhorn Racing Academy', event_type:['Driving Experience'], vehicle_type:['Exotics'], free:false, registration_required:true } },
  { id:'c19', source_id:'gtacc', url:'https://gtacc.org/local-monthly-events', raw_title:'Pistons on the Square', page_age_days:null, recurrence:R([3],6), evidence:'3rd Saturday monthly; antique, classic, muscle and late-model cars and motorcycles on the Georgetown square.', extracted:{ event_name:'Pistons on the Square', venue:'Georgetown Square', city:'Georgetown', organizer:null, event_type:['Meet','Show'], vehicle_type:['Classics','American','Motorcycles','Cars'], free:true } },
  { id:'c20', source_id:'ci', url:'https://communityimpact.com/south-central-austin/events/check-out-these-6-area-car-shows/', raw_title:'Pistons on the Square', page_age_days:850, recurrence:R([3],6), evidence:'3rd Saturday, 8–10 a.m., free, 710 S. Main St., Georgetown.', extracted:{ event_name:'Pistons on the Square', start_time:'08:00', end_time:'10:00', venue:'Georgetown Square', street_address:'710 S Main St', city:'Georgetown', event_type:['Meet','Show'], vehicle_type:['Classics','American','Motorcycles'], free:true } },
  { id:'c21', source_id:'ctxm', url:'https://www.centraltexasmopars.com/events-1', raw_title:'Pistons on the Square - Georgetown, TX', page_age_days:null, recurrence:R([3],6), evidence:'Club calendar lists it as "Multiple Dates".', extracted:{ event_name:'Pistons on the Square', city:'Georgetown', event_type:['Show'], vehicle_type:['Classics'] } },
  { id:'c22', source_id:'goroundrock', url:'https://goroundrock.com/events/round-rock-car-show-2/2026-09-20/', raw_title:'Round Rock Car Show — October 18 @ 9:00 am - 12:00 pm', page_age_days:103, evidence:'Related-events list gives explicit instances: Oct 18, Nov 15 and Dec 20, 9am–12pm.', extracted:{ event_name:'Round Rock Car Show', start_date:'2026-10-18', start_time:'09:00', end_time:'12:00', city:'Round Rock', event_type:['Show'], vehicle_type:['Classics','Cars','Mixed'] } },
  { id:'c23', source_id:'motortexas', url:'http://www.motortexas.com/event/324', raw_title:'Round Rock Car Show - Monthly', page_age_days:null, recurrence:R([3],0), evidence:'Hosted by the Round Rock Police Officers Association and the City of Round Rock. 3rd Sunday, 9AM–12PM, 301 W Bagdad (Centennial Plaza).', extracted:{ event_name:'Round Rock Car Show', start_time:'09:00', end_time:'12:00', venue:'Centennial Plaza', street_address:'301 W Bagdad Ave', city:'Round Rock', organizer:'Round Rock Police Officers Association', event_type:['Show'], vehicle_type:['Mixed'], free:true } },
  { id:'c24', source_id:'gtacc', url:'https://gtacc.org/local-monthly-events', raw_title:'Round Rock Car Show', page_age_days:null, recurrence:R([3],0), evidence:'3rd Sunday; show-and-shine, no entry fee. Time block reads "1:00 pm" but the layout is ambiguous.', extracted:{ event_name:'Round Rock Car Show', start_time:'13:00', street_address:'301 Baghdad Road', city:'Round Rock', organizer:'Round Rock Police Officers Association', event_type:['Show'], vehicle_type:['Mixed'], free:true } },
  { id:'c25', source_id:'gog', url:'https://www.getoutgarage.com/events/car-club-meetups/TX/pflugerville', raw_title:'Round Rock Car Show - Monthly', page_age_days:null, recurrence:R([3],0), evidence:'Centennial Plaza, 301 W Bagdad Ave; last listed instance Jun 21, 2026 at 8:00 AM.', extracted:{ event_name:'Round Rock Car Show', start_time:'08:00', venue:'Centennial Plaza', street_address:'301 W Bagdad Ave', city:'Round Rock', event_type:['Show'], vehicle_type:['Mixed'] } },
  { id:'c26', source_id:'ci', url:'https://communityimpact.com/south-central-austin/events/check-out-these-6-area-car-shows/', raw_title:"(untitled listing) Austin's REVL — first Sunday", page_age_days:850, recurrence:R([1],0), evidence:'"Everything on wheels" monthly meet: first Sunday, 8–11 a.m., free, charity each month. Address given as 16231 I-35, Pflugerville.', extracted:{ event_name:"Austin's REVL first-Sunday meet", start_time:'08:00', end_time:'11:00', venue:"Austin's REVL Park", street_address:'16231 I-35', city:'Pflugerville', event_type:['Meet','Cars & Coffee'], vehicle_type:['Mixed','Classics'], free:true } },
  { id:'c27', source_id:'gtacc', url:'https://gtacc.org/local-monthly-events', raw_title:'1st Sunday of Each Month — Austin\'s REVL Park', page_age_days:null, recurrence:R([1],0), evidence:'1st Sunday, 8:00 am – 11:00 am, Austin\'s REVL Park, 6231 Interstate 35, Pflugerville.', extracted:{ event_name:"Austin's REVL Park monthly meet", start_time:'08:00', end_time:'11:00', venue:"Austin's REVL Park", street_address:'6231 Interstate 35', city:'Pflugerville', event_type:['Meet'], vehicle_type:['Mixed'] } },
  { id:'c28', source_id:'ctxm', url:'https://www.centraltexasmopars.com/events-1', raw_title:'Pistons at the Park 2025', page_age_days:null, evidence:'Dated Sun Oct 05 (2025), "Austin\'s Park".', extracted:{ event_name:'Pistons at the Park', start_date:'2025-10-05', venue:"Austin's Park", city:'Pflugerville', event_type:['Show'], vehicle_type:['Mixed'] } },
  { id:'c29', source_id:'ccf', url:'https://carcruisefinder.com/car-shows/tag/pflugerville-tx/', raw_title:'Freddy’s Monthly Cruise In', page_age_days:20, evidence:'Featured for Oct 24, 2026, Pflugerville, 5:00 pm.', extracted:{ event_name:"Freddy's Monthly Cruise In", start_date:'2026-10-24', start_time:'17:00', city:'Pflugerville', event_type:['Cruise','Meet'], vehicle_type:['Mixed'] } },
  { id:'c30', source_id:'ccf', url:'https://carcruisefinder.com/car-shows/tag/pflugerville-tx/', raw_title:'P.A.W.S. Trunk or Treat 2026', page_age_days:20, evidence:'Car-show listing at Heritage Park, Pflugerville, Oct 24, 2026.', extracted:{ event_name:'P.A.W.S. Trunk or Treat', start_date:'2026-10-24', venue:'Heritage Park', city:'Pflugerville', event_type:['Show'], vehicle_type:['Mixed'], family_friendly:true } },
  { id:'c31', source_id:'gog', url:'https://www.getoutgarage.com/events/car-shows/tx/round-rock', raw_title:'The Blend & Burnout Expo 2026', page_age_days:null, evidence:'Sat Oct 24, 2026 at 9:00 AM. Venue and city are not shown in the indexed snippet.', extracted:{ event_name:'The Blend & Burnout Expo', start_date:'2026-10-24', start_time:'09:00', city:null, event_type:['Show'], vehicle_type:['Mixed'] } },
  { id:'c32', source_id:'gog', url:'https://www.getoutgarage.com/events/car-club-meetups/TX/pflugerville', raw_title:'The Blend & Burnout Expo 2026', page_age_days:null, evidence:'Same event on the Pflugerville meetups page.', extracted:{ event_name:'The Blend & Burnout Expo', start_date:'2026-10-24', start_time:'09:00', city:null, event_type:['Show'], vehicle_type:['Mixed'] } },
  { id:'c33', source_id:'gog', url:'https://www.getoutgarage.com/events/car-shows/tx/round-rock', raw_title:'VW Harvest Car Show', page_age_days:null, evidence:'Mon, Oct 26, 2026 @ 8:00 AM, Hutto Brushy Creek Amphitheater, 1001 Co Rd 137.', extracted:{ event_name:'VW Harvest Car Show', start_date:'2026-10-26', start_time:'08:00', venue:'Brushy Creek Amphitheater', street_address:'1001 Co Rd 137', city:'Hutto', event_type:['Show'], vehicle_type:['Euro','Classics'] } },
  { id:'c34', source_id:'motortexas', url:'http://www.motortexas.com/event/324', raw_title:'VW Harvest Weekend, Hutto', page_age_days:null, evidence:'Linked under "more events". No date in snippet.', extracted:{ event_name:'VW Harvest Weekend', city:'Hutto', event_type:['Show'], vehicle_type:['Euro'] } },
  { id:'c35', source_id:'motortexas', url:'http://www.motortexas.com/event/324', raw_title:'Hot Rod Night at Top Notch Hutto', page_age_days:null, evidence:'Linked under "more events". No date or schedule in snippet.', extracted:{ event_name:'Hot Rod Night at Top Notch', venue:'Top Notch', city:'Hutto', event_type:['Meet'], vehicle_type:['Classics','American'] } },
  { id:'c36', source_id:'gtacc', url:'https://gtacc.org/local-monthly-events', raw_title:'Trucks & Tri-Fives Georgetown', page_age_days:null, recurrence:R([4],0), evidence:'4th Sunday, 501 S Austin Ave, Georgetown (across from Monument Cafe). No time shown.', extracted:{ event_name:'Trucks & Tri-Fives', street_address:'501 S Austin Ave', city:'Georgetown', event_type:['Meet','Show'], vehicle_type:['Trucks','Classics','American'] } },
  { id:'c37', source_id:'ama', url:'https://austinmotoventures.com/touratexas-rally/', raw_title:'TouraTexas Rally 2026', page_age_days:149, evidence:'JSON-LD Event 2026-10-22T12:00 to 2026-10-25T10:00 at Reveille Peak Ranch. ADV rally with rides, demos and clinics.', extracted:{ event_name:'TouraTexas Rally', start_date:'2026-10-22', end_date:'2026-10-25', start_time:'12:00', end_time:'10:00', venue:'Reveille Peak Ranch', city:'Burnet', organizer:'Austin Moto Adventures', event_type:['Rally','Off-road','Group Ride'], vehicle_type:['Motorcycles','Off-road'], registration_required:true } },
  { id:'c38', source_id:'cowboyhd', url:'https://www.cowboyharleyaustin.com/events-calendar-harley-davidson-dealership--xlistevents', raw_title:'Bike Night at Bouldin Acres', page_age_days:250, recurrence:R([2,4],3), evidence:'Every 2nd and 4th Wednesday, 7–10 PM, 10400 Menchaca Rd. All bikers and clubs welcome.', extracted:{ event_name:'Bike Night at Bouldin Acres', start_time:'19:00', end_time:'22:00', venue:'Bouldin Acres', street_address:'10400 Menchaca Rd', city:'Austin', region:'South Austin', organizer:"Cowboy Harley-Davidson of Austin", event_type:['Bike Night'], vehicle_type:['Motorcycles','American'], free:true } },
  { id:'c39', source_id:'cowboyhd', url:'https://www.cowboyharleyaustin.com/events-calendar-harley-davidson-dealership--xlistevents', raw_title:'Ink & Iron', page_age_days:250, recurrence:R([2],6,true), evidence:'Listed Jul 11 and Aug 8, 10AM–3PM at the dealership (10917 S I-35). Engine inferred a 2nd-Saturday pattern; the source does not state one.', extracted:{ event_name:'Ink & Iron', start_time:'10:00', end_time:'15:00', venue:"Cowboy Harley-Davidson of Austin", street_address:'10917 S I-35 Frontage Rd', city:'Austin', region:'South Austin', organizer:"Cowboy Harley-Davidson of Austin", event_type:['Dealer Event','Show'], vehicle_type:['Motorcycles'] } },
  { id:'c40', source_id:'bnusa', url:'https://bikenightusa.com/events/view/kxrnWm8pLg/cycle-gear-austin-june-bike-night', raw_title:'Cycle Gear Austin June Bike Night', page_age_days:null, recurrence:R([2],2), evidence:'"Every second Tuesday of the month from 5-7pm." Store address not shown.', extracted:{ event_name:'Cycle Gear Austin Bike Night', start_time:'17:00', end_time:'19:00', venue:'Cycle Gear Austin', city:'Austin', organizer:'Cycle Gear Austin', event_type:['Bike Night','Dealer Event'], vehicle_type:['Motorcycles'] } },
  { id:'c41', source_id:'meetup', url:'https://www.meetup.com/find/us--tx--austin/motorcycle-riding/', raw_title:'Thursday Food and Drinks Meetup: South @ Central Machine Works', page_age_days:null, evidence:'Motogarden Bike Nights on Thursdays at Central Machine Works. Indexed instance is Jul 16. Cadence unclear ("Monthly").', extracted:{ event_name:'Motogarden Bike Night (Central Machine Works)', start_time:'18:00', venue:'Central Machine Works Brewery', street_address:'4824 E Cesar Chavez St', city:'Austin', organizer:null, event_type:['Bike Night'], vehicle_type:['Motorcycles'] } },
  { id:'c42', source_id:'txscca', url:'https://www.texasscca.org/', raw_title:'Autocross/Solo – Event #8 – 1/4 Cone at a Time', page_age_days:null, flags:['source_internal_conflict'], evidence:'Page text says Oct 12, 7–9 PM, but JSON-LD says 2026-10-04. Lone Star Park, Grand Prairie.', extracted:{ event_name:'TXR SCCA Solo E8', start_date:'2026-10-04', venue:'Lone Star Park', city:'Grand Prairie', organizer:'Texas Region SCCA', event_type:['Autocross'], vehicle_type:['Cars'] } },
  { id:'c43', source_id:'lsru', url:'https://lonestarroundup.com/pressrelease', raw_title:'23rd Annual Lonestar Round Up – April 17 & 18, 2026', page_age_days:null, evidence:'April 17–18, 2026 at the Travis County Expo Center. Swap meet and car corral (1963 and earlier).', extracted:{ event_name:'Lonestar Rod & Kustom Round Up', start_date:'2026-04-17', end_date:'2026-04-18', venue:'Travis County Exposition Center', street_address:'7311 Decker Ln', city:'Austin', organizer:'Lonestar Round Up', event_type:['Show','Swap Meet'], vehicle_type:['Classics','American'], price:'$20 wristband' } },
  { id:'c44', source_id:'culturemap', url:'https://austin.culturemap.com/eventdetail/the-lonestar-round-up/', raw_title:'The Lonestar Round Up', page_age_days:180, evidence:'Event detail for the 23rd edition at the Travis County Expo Center. $20 wristband.', extracted:{ event_name:'Lonestar Rod & Kustom Round Up', start_date:'2026-04-17', end_date:'2026-04-18', venue:'Travis County Exposition Center', street_address:'7311 Decker Ln', city:'Austin', event_type:['Show','Swap Meet'], vehicle_type:['Classics'] } },
  { id:'c45', source_id:'ctxm', url:'https://www.centraltexasmopars.com/events-1', raw_title:'Marble Falls Main Street Car Show', page_age_days:null, evidence:'Dated Sat Oct 04 in a 2025 calendar snapshot.', extracted:{ event_name:'Marble Falls Main Street Car Show', start_date:'2025-10-04', city:'Marble Falls', event_type:['Show'], vehicle_type:['Mixed'] } },
  { id:'c46', source_id:'ctxm', url:'https://www.centraltexasmopars.com/events-1', raw_title:'Coffee with Cars - Dripping Springs', page_age_days:null, evidence:'"Multiple Dates"; snapshot instance Sun Sep 28 (2025) at Moxie Gymnastics and Cheer.', extracted:{ event_name:'Coffee with Cars — Dripping Springs', start_date:'2025-09-28', venue:'Moxie Gymnastics and Cheer', city:'Dripping Springs', event_type:['Cars & Coffee'], vehicle_type:['Mixed'] } },
  { id:'c47', source_id:'ctxm', url:'https://www.centraltexasmopars.com/events-1', raw_title:'Mopar Monday: CTXM Meet and Greet', page_age_days:null, evidence:'Dated Mon Oct 06 (2025), Pflugerville.', extracted:{ event_name:'Mopar Monday — CTXM Meet and Greet', start_date:'2025-10-06', city:'Pflugerville', organizer:'Central Texas Mopars', event_type:['Club Event','Meet'], vehicle_type:['American'] } },
  { id:'c48', source_id:'ctxm', url:'https://www.centraltexasmopars.com/events-1', raw_title:'Craft and Cars - Growler Bar - Pflugerville, TX', page_age_days:null, evidence:'"Multiple Dates". No schedule in snippet.', extracted:{ event_name:'Craft and Cars', venue:'Growler Bar', city:'Pflugerville', event_type:['Meet'], vehicle_type:['Mixed'] } },
  { id:'c49', source_id:'breakfastclub', url:'https://breakfastclubatx.com/', raw_title:'Breakfast Club — monthly group ride', page_age_days:688, evidence:'Bicycle group rides from Central Machine Works, once a month on a Saturday.', extracted:{ event_name:'Breakfast Club group ride', venue:'Central Machine Works', city:'Austin', event_type:['Group Ride'], vehicle_type:[], motorized:false } },
  { id:'c50', source_id:'ccf', url:'https://carcruisefinder.com/car-shows/tag/pflugerville-tx/', raw_title:'Pflugerville Coffee & Pfuel', page_age_days:20, recurrence:R([1],6), evidence:'Oct 3, 2026 (yesterday). First Saturday monthly, 9–11 a.m., downtown Pflugerville, free.', extracted:{ event_name:'Pflugerville Coffee & Pfuel', start_time:'09:00', end_time:'11:00', venue:'Downtown Pflugerville', street_address:'100 E Main St', city:'Pflugerville', organizer:'City of Pflugerville', event_type:['Cars & Coffee'], vehicle_type:['Classics','Mixed'], free:true } }
].map(c => ({ ...c, discovered_at:T, last_checked_at:T, processing_state:'extracted' }));
