// Server-rendered, indexable MorrMoto pages. Pure functions: give them published events, get HTML back.
const SITE = 'https://www.morrmoto.com';
const MO = ['January','February','March','April','May','June','July','August','September','October','November','December'];
const WD = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const D = s => new Date(s + 'T12:00:00Z');
const slugify = s => String(s).normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/&/g, ' and ').replace(/['’]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 70).replace(/-+$/, '');
const t12 = t => { if (!t) return ''; let [h, m] = t.split(':').map(Number); const ap = h >= 12 ? 'PM' : 'AM'; h = h % 12 || 12; return h + (m ? ':' + String(m).padStart(2, '0') : '') + ' ' + ap; };
// America/Chicago offset for a date (CDT -05:00 2nd Sun Mar – 1st Sun Nov, else CST -06:00)
const nthSun = (y, mo, n) => { const d = new Date(Date.UTC(y, mo, 1)); const first = (7 - d.getUTCDay()) % 7 + 1; return first + (n - 1) * 7; };
const offset = iso => { const [y, m, d] = iso.split('-').map(Number); const a = Date.UTC(y, 2, nthSun(y, 2, 2)), b = Date.UTC(y, 10, nthSun(y, 10, 1)), t = Date.UTC(y, m - 1, d); return t >= a && t < b ? '-05:00' : '-06:00'; };
const ldDate = (d, t) => t ? d + 'T' + t + ':00' + offset(d) : d;
export const CATS = {
  'cars': { label: 'Car events', h: 'Car events in Austin', test: e => (e.vehicle_type || []).some(v => /Cars|Mixed|Classics|Exotics|JDM|Euro|American|Trucks/.test(v)) },
  'motorcycles': { label: 'Motorcycle events', h: 'Motorcycle events in Austin', test: e => (e.vehicle_type || []).includes('Motorcycles') },
  'cars-and-coffee': { label: 'Cars & Coffee', h: 'Cars & Coffee in Austin', test: e => (e.event_type || []).includes('Cars & Coffee') },
  'bike-nights': { label: 'Bike nights', h: 'Bike nights in Austin', test: e => (e.event_type || []).some(t => /Bike Night/i.test(t)) },
  'track-days': { label: 'Track days + racing', h: 'Track days and racing in Austin', test: e => (e.event_type || []).some(t => /Track|Race|Racing|Autocross|Major Motorsport/i.test(t)) },
  'car-shows': { label: 'Car shows', h: 'Car shows in Austin', test: e => (e.event_type || []).some(t => /Show/i.test(t)) },
  'off-road': { label: 'Off-road', h: 'Off-road events around Austin', test: e => (e.vehicle_type || []).some(v => /Off/i.test(v)) || (e.event_type || []).some(t => /Off|Rally/i.test(t)) }
};
export const MIN_INDEX = 3;
export function publish(r, today) {
  const pub = r.events.filter(e => !e.beyond && e.f.date && ['Verified', 'Likely'].includes(e.state) && !(e.state === 'Likely' && e.dupes.length) && (e.f.end || e.f.date) >= today)
    .sort((a, b) => (a.f.date + (a.f.start_time || '99')).localeCompare(b.f.date + (b.f.start_time || '99')));
  const seen = new Map();
  for (const e of pub) { const d = D(e.f.date); let s = slugify(e.f.title + ' ' + MO[d.getUTCMonth()] + ' ' + d.getUTCDate() + ' ' + d.getUTCFullYear()); if (seen.has(s)) s += '-' + e.id; seen.set(s, 1); e.slug = s; }
  return pub;
}
const whenText = f => { const d = D(f.date); let s = WD[d.getUTCDay()] + ', ' + MO[d.getUTCMonth()] + ' ' + d.getUTCDate(); if (f.end && f.end !== f.date) { const e = D(f.end); s += ' – ' + WD[e.getUTCDay()] + ', ' + MO[e.getUTCMonth()] + ' ' + e.getUTCDate(); } if (f.start_time) s += ' · ' + t12(f.start_time) + (f.end_time ? ' – ' + t12(f.end_time) : ''); return s + ', ' + d.getUTCFullYear(); };
const kindOf = e => (e.event_type || [])[0] || 'Motor event';
const srcOf = e => { const o = (e.occs || [])[0] || {}; return { name: (o.src && o.src.name) || e.f.organizer || 'Source', url: o.url || (o.cand && o.cand.url) || '' }; };
const costOf = f => f.free === true ? 'Free' : f.price ? f.price : f.registration_required ? 'Registration' : '';
const mapsUrl = f => 'https://www.google.com/maps/search/?api=1&query=' + encodeURIComponent([f.venue, f.street_address, f.city, 'TX'].filter(Boolean).join(', '));
export function eventLd(e) {
  const f = e.f, s = srcOf(e);
  const ld = { '@context': 'https://schema.org', '@type': 'Event', name: f.title, startDate: ldDate(f.date, f.start_time), endDate: ldDate(f.end || f.date, f.end_time || (f.end && f.end !== f.date ? null : null)),
    eventStatus: e.lifecycle === 'Canceled' ? 'https://schema.org/EventCancelled' : 'https://schema.org/EventScheduled', eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode',
    location: { '@type': 'Place', name: f.venue || f.city, address: { '@type': 'PostalAddress', ...(f.street_address ? { streetAddress: f.street_address } : {}), addressLocality: f.city, addressRegion: 'TX', addressCountry: 'US' } },
    url: SITE + '/events/' + e.slug };
  if (f.latitude && f.longitude) ld.location.geo = { '@type': 'GeoCoordinates', latitude: f.latitude, longitude: f.longitude };
  if (f.organizer) ld.organizer = { '@type': 'Organization', name: f.organizer, ...(s.url ? { url: s.url } : {}) };
  if (f.free === true) ld.isAccessibleForFree = true;
  if (f.registration_url || (f.free === true && s.url)) ld.offers = { '@type': 'Offer', url: f.registration_url || s.url, ...(f.free === true ? { price: 0, priceCurrency: 'USD' } : {}) };
  if (f.image_url) ld.image = [f.image_url];
  return ld;
}
const FONTS = '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Anton&family=Archivo:ital,wdth,wght@1,125,900&family=Inter:wght@400;600;700&family=JetBrains+Mono:wght@700&display=swap" rel="stylesheet">';
const CSS = ':root{color-scheme:dark;--bg:#0B0B0B;--s2:#141515;--tx:#EDE9E4;--tx2:#A8A39C;--bd:#2A2C2E;--sig:#FF4D00;--onsig:#0B0B0B;--sigt:#FF6A2B}@media (prefers-color-scheme:light){:root{color-scheme:light;--bg:#EDE9E4;--s2:#E4DFD8;--tx:#0B0B0B;--tx2:#55524D;--bd:#CFC8BE;--sig:#B23600;--sigt:#B23600;--onsig:#EDE9E4}}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--tx);font:16px/1.5 Inter,system-ui,sans-serif;-webkit-font-smoothing:antialiased}a{color:var(--tx);text-underline-offset:3px}a:hover{color:var(--sigt)}.w{max-width:760px;margin:0 auto;padding:0 24px}header{border-bottom:1px solid var(--bd)}header .w{height:60px;display:flex;align-items:center;justify-content:space-between}.lg{font:italic 900 18px Archivo,sans-serif;font-stretch:125%;letter-spacing:-.02em;text-decoration:none}.lg b{color:var(--sigt);font-weight:900}.k{font:700 12px "JetBrains Mono",monospace;letter-spacing:.1em;text-transform:uppercase;color:var(--sigt)}.m{font:700 12px "JetBrains Mono",monospace;letter-spacing:.06em;text-transform:uppercase;color:var(--tx2)}h1{font:400 44px/1 Anton,sans-serif;text-transform:uppercase;margin:8px 0 0;text-wrap:balance}h2{font:400 26px/1 Anton,sans-serif;text-transform:uppercase;margin:0}dl{display:grid;grid-template-columns:auto 1fr;gap:10px 20px;margin:28px 0;padding:20px;border-radius:10px;background:var(--s2)}dt{font:700 11px "JetBrains Mono",monospace;letter-spacing:.1em;text-transform:uppercase;color:var(--tx2);padding-top:3px}dd{margin:0;font-weight:600}.b{display:flex;flex-wrap:wrap;gap:8px}.btn{display:inline-flex;align-items:center;min-height:48px;padding:0 20px;border-radius:999px;font-weight:700;text-decoration:none;box-shadow:inset 0 0 0 1px var(--bd)}.btn.p{background:var(--sig);color:var(--onsig,#0B0B0B);box-shadow:none}ul.l{list-style:none;margin:0;padding:0}ul.l li{border-bottom:1px solid var(--bd)}ul.l a{display:grid;grid-template-columns:88px 1fr;gap:16px;padding:16px 0;text-decoration:none}.dt{font:700 12px/1.3 "JetBrains Mono",monospace;letter-spacing:.06em;text-transform:uppercase;color:var(--tx2)}.tt{font-weight:700;font-size:17px}.vn{color:var(--tx2);font-size:14px}footer{margin:56px 0 40px;color:var(--tx2);font-size:14px}nav.c{display:flex;flex-wrap:wrap;gap:8px;margin:20px 0}nav.c a{font:700 12px "JetBrains Mono",monospace;letter-spacing:.06em;text-transform:uppercase;padding:8px 12px;border-radius:999px;box-shadow:inset 0 0 0 1px var(--bd);text-decoration:none}';
const shell = ({ title, desc, path, body, ld, noindex }) => '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>' + esc(title) + '</title><meta name="description" content="' + esc(desc) + '"><link rel="canonical" href="' + SITE + path + '">' + (noindex ? '<meta name="robots" content="noindex,follow">' : '') + '<meta property="og:type" content="website"><meta property="og:site_name" content="MorrMoto"><meta property="og:title" content="' + esc(title) + '"><meta property="og:description" content="' + esc(desc) + '"><meta property="og:url" content="' + SITE + path + '"><meta property="og:image" content="' + SITE + '/brand/motion-mark/icon-512.png"><meta name="twitter:card" content="summary"><meta name="theme-color" content="#0B0B0B"><link rel="icon" href="/brand/motion-mark/favicon.svg" type="image/svg+xml">' + FONTS + '<style>' + CSS + '</style>' + (ld ? '<script type="application/ld+json">' + JSON.stringify(ld).replace(/</g, '\\u003c') + '</script>' : '') + '</head><body><header><div class="w"><a class="lg" href="/">MORR<b>MOTO</b></a><a class="m" href="/" style="text-decoration:none">Open MorrMoto →</a></div></header><main class="w">' + body + '</main><div class="w"><footer>MorrMoto finds motor events around Austin every morning and links each one back to its source. <a href="/austin/this-weekend">This weekend</a> · <a href="/austin">Everything around Austin</a></footer></div></body></html>';
const row = e => { const d = D(e.f.date); return '<li><a href="/events/' + e.slug + '"><span class="dt">' + WD[d.getUTCDay()].slice(0, 3) + ' ' + MO[d.getUTCMonth()].slice(0, 3) + ' ' + d.getUTCDate() + (e.f.start_time ? '<br>' + t12(e.f.start_time) : '') + '</span><span><span class="m">' + esc(kindOf(e)) + '</span><br><span class="tt">' + esc(e.f.title) + '</span><br><span class="vn">' + esc([e.f.venue, e.f.city].filter(Boolean).join(' · ')) + (costOf(e.f) ? ' · ' + esc(costOf(e.f)) : '') + '</span></span></a></li>'; };
const catNav = (pub, cur) => '<nav class="c" aria-label="Categories"><a href="/austin/this-weekend">This weekend</a>' + Object.entries(CATS).filter(([k, c]) => pub.filter(c.test).length >= MIN_INDEX).map(([k, c]) => '<a href="/austin/' + k + '"' + (k === cur ? ' aria-current="page"' : '') + '>' + esc(c.label) + '</a>').join('') + '</nav>';
export function eventPage(e, pub) {
  const f = e.f, s = srcOf(e), cost = costOf(f), d = D(f.date);
  const desc = kindOf(e) + ' at ' + (f.venue || f.city) + ', ' + f.city + ', TX on ' + MO[d.getUTCMonth()] + ' ' + d.getUTCDate() + (f.start_time ? ' at ' + t12(f.start_time) : '') + '. ' + (cost ? cost + '. ' : '') + 'Found and checked by MorrMoto.';
  const more = pub.filter(x => x !== e).slice(0, 6);
  const body = '<p class="k" style="margin:32px 0 0">' + esc(kindOf(e)) + (e.lifecycle === 'Canceled' ? ' · Canceled' : '') + '</p><h1>' + esc(f.title) + '</h1>'
    + '<dl><dt>When</dt><dd>' + esc(whenText(f)) + '</dd><dt>Where</dt><dd>' + esc([f.venue, f.street_address, f.city + ', TX'].filter(Boolean).join(' · ')) + '</dd>' + (cost ? '<dt>Cost</dt><dd>' + esc(cost) + '</dd>' : '') + (f.organizer ? '<dt>Organizer</dt><dd>' + esc(f.organizer) + '</dd>' : '') + ((e.vehicle_type || []).length ? '<dt>What</dt><dd>' + esc(e.vehicle_type.join(', ')) + '</dd>' : '') + '<dt>Trust</dt><dd>' + esc(e.state === 'Verified' ? 'Verified · ' + e.occs.length + ' sources' : e.occs.length > 1 ? 'We found this in ' + e.occs.length + ' places' : 'From the source') + '</dd></dl>'
    + '<div class="b"><a class="btn p" href="' + esc(mapsUrl(f)) + '" rel="noopener">Get there</a>' + (f.registration_url ? '<a class="btn" href="' + esc(f.registration_url) + '" rel="noopener nofollow">Register</a>' : '') + (s.url ? '<a class="btn" href="' + esc(s.url) + '" rel="noopener nofollow">Open original →</a>' : '') + '</div>'
    + '<p class="m" style="margin-top:20px">From the source: ' + esc(s.name) + '. Always confirm details with the organizer.</p>'
    + (more.length ? '<section style="margin-top:48px"><h2>Also moving around Austin</h2><ul class="l">' + more.map(row).join('') + '</ul></section>' : '');
  return shell({ title: f.title + ' · ' + MO[d.getUTCMonth()] + ' ' + d.getUTCDate() + ', ' + d.getUTCFullYear() + ' · ' + f.city + ' | MorrMoto', desc, path: '/events/' + e.slug, body, ld: eventLd(e) });
}
const itemList = (list, path) => ({ '@context': 'https://schema.org', '@type': 'ItemList', url: SITE + path, itemListElement: list.slice(0, 50).map((e, i) => ({ '@type': 'ListItem', position: i + 1, url: SITE + '/events/' + e.slug, name: e.f.title })) });
export function weekendDays(today) { const t = D(today), dow = t.getUTCDay(); const add = n => new Date(t.getTime() + n * 864e5).toISOString().slice(0, 10); const fri = dow === 0 ? add(-2) : dow === 6 ? add(-1) : add(5 - dow); const f = D(fri); return [0, 1, 2].map(n => new Date(f.getTime() + n * 864e5).toISOString().slice(0, 10)); }
const onDay = (e, d) => e.f.date <= d && (e.f.end || e.f.date) >= d;
export function weekendPage(pub, today) {
  const days = weekendDays(today), list = pub.filter(e => days.some(d => onDay(e, d)));
  const counts = days.map(d => WD[D(d).getUTCDay()] + ' · ' + pub.filter(e => onDay(e, d)).length).join('   ');
  const body = '<p class="k" style="margin:32px 0 0">This weekend · ' + MO[D(days[0]).getUTCMonth()] + ' ' + D(days[0]).getUTCDate() + '–' + D(days[2]).getUTCDate() + '</p><h1>Motor events in Austin this weekend</h1><p class="m" style="margin-top:12px">' + list.length + ' thing' + (list.length === 1 ? '' : 's') + ' happening. ' + esc(counts) + '</p>' + catNav(pub)
    + (list.length ? days.map(d => { const l = pub.filter(e => onDay(e, d)); return l.length ? '<section style="margin-top:28px"><h2>' + WD[D(d).getUTCDay()] + '</h2><ul class="l">' + l.map(row).join('') + '</ul></section>' : ''; }).join('') : '<p style="margin-top:28px">Nothing moving this weekend yet. <a href="/austin">See everything coming up →</a></p>');
  return shell({ title: 'Car Shows, Meets & Motor Events in Austin This Weekend | MorrMoto', desc: 'Car shows, Cars & Coffee, bike nights, track days and races happening around Austin this weekend. ' + list.length + ' found and checked.', path: '/austin/this-weekend', body, ld: itemList(list, '/austin/this-weekend'), noindex: list.length < 1 });
}
export function listPage(pub, key) {
  const c = key ? CATS[key] : null, list = c ? pub.filter(c.test) : pub, path = '/austin' + (key ? '/' + key : '');
  const h = c ? c.h : 'Motor events around Austin';
  const body = '<p class="k" style="margin:32px 0 0">Around Austin · Next 30 days</p><h1>' + esc(h) + '</h1><p class="m" style="margin-top:12px">' + list.length + ' thing' + (list.length === 1 ? '' : 's') + ' coming up.</p>' + catNav(pub, key) + (list.length ? '<ul class="l">' + list.map(row).join('') + '</ul>' : '<p>Nothing moving here yet. <a href="/austin">See everything →</a></p>');
  const title = c ? h + ' | MorrMoto' : 'Motor Events in Austin, TX: Car Shows, Bike Nights & Track Days | MorrMoto';
  return shell({ title, desc: (c ? c.label + ' around Austin and Central Texas: ' : 'Car shows, Cars & Coffee, motorcycle rides, bike nights, track days and races around Austin and Central Texas: ') + list.length + ' coming up, each linked to its source.', path, body, ld: itemList(list, path), noindex: list.length < MIN_INDEX });
}
export function sitemap(pub) {
  const urls = ['/', '/how-it-works', '/austin', '/austin/this-weekend', ...Object.entries(CATS).filter(([k, c]) => pub.filter(c.test).length >= MIN_INDEX).map(([k]) => '/austin/' + k), ...pub.map(e => '/events/' + e.slug)];
  return '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + urls.map(u => '  <url><loc>' + SITE + u + '</loc></url>').join('\n') + '\n</urlset>\n';
}
export function notFound() { return shell({ title: 'Not moving anymore | MorrMoto', desc: 'This event isn’t on MorrMoto anymore.', path: '/', noindex: true, body: '<h1 style="margin-top:40px">This one’s not moving anymore.</h1><p>It may have passed or been taken down.</p><p><a class="btn p" href="/">See what’s moving</a></p>' }); }
export function staticList(pub) { return pub.slice(0, 40).map(e => '<li><a href="/events/' + e.slug + '">' + esc(e.f.title) + '</a> · ' + esc(whenText(e.f)) + ' · ' + esc([e.f.venue, e.f.city].filter(Boolean).join(', ')) + '</li>').join(''); }

const page = (path, title, desc, h, body) => shell({ title, desc, path, body: '<p class="k" style="margin:32px 0 0">MorrMoto</p><h1>' + h + '</h1>' + body });
const P = t => '<p style="max-width:62ch;text-wrap:pretty">' + t + '</p>';
const H = t => '<h2 style="margin-top:32px">' + t + '</h2>';
const REVIEW = '<p class="m" style="margin-top:40px">Draft · needs legal review before public launch.</p>';
export const TRUST = {
  'how-it-works': () => page('/how-it-works', 'How MorrMoto Works | Motor Events in Austin', 'How MorrMoto finds, checks and links Austin car shows, bike nights, track days and motor events.', 'How MorrMoto works',
    P('Motor culture is scattered everywhere. Organizer sites. Clubs. Tracks. Shops. Social posts. Community calendars.') + P('MorrMoto looks across those sources, connects what it finds and keeps checking for changes. So you don’t have to.')
    + '<dl><dt>We find it</dt><dd>Every morning we check track calendars, clubs, venues and public event pages around Austin.</dd><dt>We check it</dt><dd>Duplicates get merged. Details are compared across sources. Anything unclear waits for a person.</dd><dt>You go</dt><dd>Every event links back to where we found it, so you can confirm with the organizer.</dd></dl>'
    + P('Spot something off? Open the event and tap <strong>Something wrong?</strong> Run an event? Tap <strong>This is my event</strong>.') + '<p style="font:400 32px/1 Anton,sans-serif;text-transform:uppercase;margin-top:32px">Know what’s moving.</p>'),
  privacy: () => page('/privacy', 'Privacy | MorrMoto', 'What MorrMoto collects and why.', 'Privacy',
    P('Short version: we collect as little as we can.') + H('On your device') + P('Saved events, your area, your scenes and your theme are stored in your browser. They aren’t sent to us. Clear your browser data and they’re gone.')
    + H('Usage') + P('We count anonymous product events (for example, an event opened, a filter used, a Get There tap) with a random session ID so we can see what’s useful. We use Vercel Web Analytics for page visits. Neither uses advertising cookies or builds a profile of you.')
    + H('Location') + P('If you tap Use my location, your browser shares your position with the page to measure distances. It stays on your device. We don’t store it.')
    + H('Things you send us') + P('If you add an event, report a problem or contact us, we keep what you send, including your email if you give one, to review it and reply. Ask and we’ll delete it.')
    + H('Contact') + P('Questions or deletion requests: use the <a href="/contact">contact page</a>.') + REVIEW),
  terms: () => page('/terms', 'Terms | MorrMoto', 'Terms for using MorrMoto.', 'Terms',
    P('MorrMoto is a free guide to motor events around Austin. Using it means you agree to these terms.') + H('Events are listed, not run, by us') + P('We find events from public sources and link back to them. Organizers can change or cancel at any time. Always confirm details with the organizer before you go. We aren’t responsible for events, venues, tickets or anything that happens there.')
    + H('Accuracy') + P('We work to keep details right, and we flag what we can’t confirm. We can still be wrong. If you spot a problem, tell us from the event page.')
    + H('Your submissions') + P('When you add or correct an event, you confirm it’s accurate to your knowledge and let us publish those event facts with a link to the source.')
    + H('Content and takedowns') + P('Event names, dates and places are facts we link to their source. Images shown on an event come from that event’s own page and are credited. If you own content and want it removed, use the <a href="/contact">contact page</a> and we’ll act promptly.')
    + H('Changes') + P('We may update these terms as MorrMoto grows. The date below shows the latest version.') + '<p class="m">Last updated October 2026</p>' + REVIEW),
  contact: () => page('/contact', 'Contact, Corrections + Takedowns | MorrMoto', 'Contact MorrMoto, correct an event, or request removal of an event or image.', 'Contact',
    P('Fastest fixes happen from the event itself: open it and tap <strong>Something wrong?</strong> or <strong>This is my event</strong>.')
    + H('Everything else') + '<form id="f" style="display:grid;gap:12px;max-width:520px;margin-top:16px"><label class="m">What’s this about<select name="reason" required style="display:block;width:100%;margin-top:6px;min-height:48px;font:16px Inter,sans-serif;padding:0 10px;background:var(--s2);color:var(--tx);border:1px solid var(--bd);border-radius:4px"><option value="Contact">General feedback</option><option value="Takedown">Remove my content or image</option><option value="Remove this event">Remove my event</option><option value="Other">Something else</option></select></label><label class="m">Your email<input name="email" type="email" required autocomplete="email" style="display:block;width:100%;margin-top:6px;min-height:48px;font:16px Inter,sans-serif;padding:0 10px;background:var(--s2);color:var(--tx);border:1px solid var(--bd);border-radius:4px"></label><label class="m">Message<textarea name="note" required maxlength="600" rows="5" style="display:block;width:100%;margin-top:6px;font:16px Inter,sans-serif;padding:10px;background:var(--s2);color:var(--tx);border:1px solid var(--bd);border-radius:4px"></textarea></label><input name="hp" tabindex="-1" autocomplete="off" aria-hidden="true" style="position:absolute;left:-9999px"><button class="btn p" type="submit" style="border:0;cursor:pointer;justify-self:start">Send it</button><p id="st" role="status" class="m"></p></form>'
    + '<script>document.getElementById("f").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.target),st=document.getElementById("st");st.textContent="Sending…";try{const r=await fetch("/api/report",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"contact",reason:f.get("reason"),email:f.get("email"),note:f.get("note"),hp:f.get("hp"),page:"/contact"})});const j=await r.json();if(!j.ok)throw 0;e.target.reset();st.textContent="Got it. We’ll reply by email.";}catch(_){st.textContent="Couldn’t send that. Try again in a minute.";}});</script>')
};
